using System;
using System.Collections.Generic;
using System.Linq;

namespace AITeammate.Scripts;

internal static class AiBuildArchetypeCatalog
{
    private static readonly IReadOnlyList<AiBuildArchetype> Archetypes =
    [
        Build("ironclad", "strength", "Strength", AiBuildTier.S,
            ["Heavy Blade", "Inflame", "Demon Form", "Offering"],
            ["Fight Me", "Battle Trance", "Shrug It Off", "Flame Barrier", "Whirlwind", "Bludgeon", "Limit Break"],
            ["Vajra", "Burning Blood", "Bag of Marbles"],
            ["Ornamental Fan", "Pen Nib", "Meat on the Bone"],
            ["Velvet Choker", "Runic Dome", "Philosopher's Stone"]),
        Build("ironclad", "barricade", "Barricade", AiBuildTier.A,
            ["Barricade", "Body Slam", "Impervious", "Shrug It Off"],
            ["Entrench", "Flame Barrier", "Power Through", "Second Wind", "True Grit"],
            ["Calipers", "Fossilized Helix"],
            ["Anchor", "Orichalcum", "Tungsten Rod"],
            ["Philosopher's Stone"]),
        Build("ironclad", "exhaust", "Exhaust", AiBuildTier.A,
            ["Corruption", "Dark Embrace", "Feel No Pain", "Fiend Fire"],
            ["Second Wind", "True Grit", "Burning Pact", "Offering", "Seeing Red"],
            ["Dead Branch"],
            ["Charon's Ashes", "Sundial", "Medical Kit"],
            ["Velvet Choker"]),
        Build("ironclad", "bloodletting", "Bloodletting", AiBuildTier.A,
            ["Rupture", "Inferno", "Bloodletting", "Tear Asunder"],
            ["Offering", "Hemokinesis", "Combust", "Reaper", "Limit Break"],
            ["Magic Flower", "Self-Forming Clay"],
            ["Meat on the Bone", "Burning Blood", "Vajra"],
            ["Runic Dome"]),
        Build("ironclad", "strike", "Strike", AiBuildTier.B,
            ["Perfected Strike", "Twin Strike", "Pommel Strike", "Hellraiser"],
            ["Strike", "Wild Strike", "Swift Strike", "Sword Boomerang", "Inflame"],
            ["Strike Dummy", "Vajra"],
            ["Pen Nib", "Bag of Marbles"],
            ["Pandora's Box"],
            desiredMinDeckSize: 24,
            desiredMaxDeckSize: 32,
            lockCoreCardCount: 1),
        Build("ironclad", "self_wound", "Self-Wound", AiBuildTier.B,
            ["Tear Asunder", "Rupture", "Brand", "Offering"],
            ["Bloodletting", "Hemokinesis", "Combust", "Reaper", "Limit Break"],
            ["Magic Flower", "Self-Forming Clay"],
            ["Meat on the Bone", "Burning Blood"],
            ["Runic Dome"]),

        Build("silent", "poison", "Poison", AiBuildTier.S,
            ["Noxious Fumes", "Deadly Poison", "Accelerant", "Bouncing Flask"],
            ["Catalyst", "Burst", "Poisoned Stab", "Footwork", "Backflip", "Leg Sweep", "Malaise", "Corpse Explosion", "Neutralize"],
            ["Ring of the Snake", "Snecko Skull", "Silver Crucible"],
            ["Specimen", "Bag of Preparation", "Tungsten Rod", "Leafy Poultice"],
            ["Philosopher's Stone", "Ectoplasm", "Mark of Pain"]),
        Build("silent", "sly", "Sly Discard", AiBuildTier.S,
            ["Master Planner", "Acrobatics", "Prepared", "Reflex"],
            ["Tactician", "Calculated Gamble", "Concentrate", "Tools of the Trade", "Backflip", "Adrenaline", "Untouchable"],
            ["Ring of the Snake", "Tough Bandages", "Silver Crucible"],
            ["Sundial", "Bag of Preparation", "Gambling Chip", "Leafy Poultice"],
            ["Velvet Choker"],
            desiredMinDeckSize: 14,
            desiredMaxDeckSize: 22,
            lockCoreCardCount: 1,
            lockEvidenceScore: 24),
        Build("silent", "grand_finale", "Grand Finale Infinite", AiBuildTier.S,
            ["Grand Finale", "Acrobatics", "Calculated Gamble", "Tactician"],
            ["Prepared", "Reflex", "Backflip", "Concentrate", "Expertise", "Master Planner"],
            ["Ring of the Snake", "Sundial", "Silver Crucible"],
            ["Gambling Chip", "Bag of Preparation", "Peace Pipe", "Leafy Poultice"],
            ["Velvet Choker"],
            desiredMinDeckSize: 12,
            desiredMaxDeckSize: 18,
            lockCoreCardCount: 2),
        Build("silent", "shiv", "Shiv", AiBuildTier.A,
            ["Blade Dance", "Accuracy", "Cloak and Dagger", "Infinite Blades"],
            ["Finisher", "After Image", "Adrenaline", "Backflip", "Terror", "Neutralize", "Fan of Knives"],
            ["Shuriken", "Kunai", "Silver Crucible"],
            ["Ornamental Fan", "Pen Nib", "Ninja Scroll", "Leafy Poultice"],
            ["Velvet Choker"]),
        Build("silent", "envenom", "Envenom", AiBuildTier.A,
            ["Envenom", "Snakebite", "Fan of Knives", "Finisher"],
            ["Blade Dance", "Cloak and Dagger", "Accuracy", "Poisoned Stab", "Burst"],
            ["Snecko Skull", "Shuriken"],
            ["Kunai", "Specimen", "Ornamental Fan"],
            ["Velvet Choker"]),
        Build("silent", "combo_execution", "Combo Execution", AiBuildTier.A,
            ["Wraith Form", "Burst", "Nightmare", "Footwork"],
            ["Backflip", "Leg Sweep", "Malaise", "Adrenaline", "Prepared"],
            ["Tungsten Rod", "Runic Pyramid"],
            ["Bag of Preparation", "Orichalcum", "Anchor"],
            ["Philosopher's Stone"]),

        Build("defect", "lightning", "Lightning", AiBuildTier.S,
            ["Zap", "Defragment", "Echo Form", "Electrodynamics"],
            ["Ball Lightning", "Storm", "Static Discharge", "Capacitor", "Coolheaded", "Turbo"],
            ["Cracked Core", "Data Disk"],
            ["Inserter", "Bag of Preparation", "Mummified Hand"],
            ["Runic Dome"]),
        Build("defect", "claw", "Claw", AiBuildTier.S,
            ["Claw", "All for One", "Scrape", "Feral"],
            ["Go for the Eyes", "Beam Cell", "Hologram", "Turbo", "Overclock", "Rebound"],
            ["Unceasing Top", "Sundial"],
            ["Kunai", "Shuriken", "Pen Nib"],
            ["Velvet Choker"],
            desiredMinDeckSize: 14,
            desiredMaxDeckSize: 22,
            lockCoreCardCount: 1),
        Build("defect", "frost", "Frost", AiBuildTier.A,
            ["Glacier", "Defragment", "Coolheaded", "Capacitor"],
            ["Cold Snap", "Loop", "Consume", "Echo Form", "Hologram"],
            ["Data Disk", "Inserter"],
            ["Orichalcum", "Anchor", "Tungsten Rod"],
            ["Philosopher's Stone"]),
        Build("defect", "dark_orb", "Dark Orb", AiBuildTier.A,
            ["Darkness", "Multi-Cast", "Defragment", "Consuming Shadow"],
            ["Recursion", "Dualcast", "Hologram", "Echo Form", "Capacitor"],
            ["Data Disk", "Inserter"],
            ["Runic Pyramid", "Bag of Preparation"],
            ["Velvet Choker"]),
        Build("defect", "creative_ai", "Creative AI", AiBuildTier.A,
            ["Creative AI", "Echo Form", "Storm", "Machine Learning"],
            ["Defragment", "Heatsinks", "Capacitor", "Turbo", "Hologram"],
            ["Mummified Hand", "Bird-Faced Urn"],
            ["Data Disk", "Inserter", "Bag of Preparation"],
            ["Velvet Choker"]),

        Build("regent", "forge", "Forge", AiBuildTier.S,
            ["Seeking Edge", "Conqueror", "Falling Star", "Sword Sage"],
            ["Forge", "Sovereign Blade", "Glow", "Convergence", "Knockout Blow"],
            ["Whetstone"],
            ["Vajra", "Pen Nib", "Bag of Preparation"],
            ["Runic Dome"]),
        Build("regent", "star_burst", "Star Burst", AiBuildTier.A,
            ["Stardust", "Seven Stars", "Glow", "Black Hole"],
            ["Big Bang", "Convergence", "Meteor Shower", "Falling Star"],
            ["Bag of Preparation", "Sundial"],
            ["Pen Nib", "Mummified Hand"],
            ["Velvet Choker"]),
        Build("regent", "void_form", "Void Form", AiBuildTier.A,
            ["Void Form", "Big Bang", "Decisions, Decisions", "Convergence"],
            ["Black Hole", "Meteor Shower", "Stardust", "Glow"],
            ["Runic Pyramid", "Snecko Eye"],
            ["Bag of Preparation", "Ice Cream"],
            ["Velvet Choker"]),
        Build("regent", "bombardment", "Bombardment", AiBuildTier.B,
            ["Bombardment", "Meteor Shower", "Gamma Blast", "Knockout Blow"],
            ["Falling Star", "Seven Stars", "Glow", "Conqueror"],
            ["Pen Nib", "Vajra"],
            ["Bag of Marbles", "Bag of Preparation"],
            ["Runic Dome"]),

        Build("necrobinder", "osty", "Osty", AiBuildTier.S,
            ["Dirge", "Invoke", "Borrowed Time", "Reanimate"],
            ["Bodyguard", "Summon", "Sacrifice", "Grave Warden", "Danse Macabre", "Lethality"],
            ["Osty's Collar"],
            ["Bag of Preparation", "Tungsten Rod", "Orichalcum"],
            ["Runic Dome"]),
        Build("necrobinder", "soul", "Soul", AiBuildTier.S,
            ["Haunt", "Soul Storm", "Death March", "Capture Spirit"],
            ["Borrowed Time", "Dirge", "Reanimate", "Grave Warden", "Danse Macabre"],
            ["Sundial", "Bag of Preparation"],
            ["Dead Branch", "Mummified Hand"],
            ["Velvet Choker"]),
        Build("necrobinder", "doom", "Doom", AiBuildTier.A,
            ["Capture Spirit", "Countdown", "Grave Warden", "Danse Macabre"],
            ["Haunt", "Borrowed Time", "Dirge", "Reanimate"],
            ["Bag of Preparation"],
            ["Runic Pyramid", "Tungsten Rod"],
            ["Velvet Choker"]),
        Build("necrobinder", "reaper", "Reaper", AiBuildTier.A,
            ["Reaper Form", "The Scythe", "Eradicate", "Lethality"],
            ["Death March", "Soul Storm", "Borrowed Time", "Capture Spirit"],
            ["Vajra", "Pen Nib"],
            ["Bag of Marbles", "Meat on the Bone"],
            ["Runic Dome"])
    ];

    public static IReadOnlyList<AiBuildArchetype> ForCharacter(string characterId)
    {
        return Archetypes
            .Where(archetype => string.Equals(archetype.CharacterId, characterId, StringComparison.OrdinalIgnoreCase))
            .ToList();
    }

    private static AiBuildArchetype Build(
        string characterId,
        string buildId,
        string displayName,
        AiBuildTier tier,
        IReadOnlyList<string> coreCards,
        IReadOnlyList<string> supportCards,
        IReadOnlyList<string> keyRelics,
        IReadOnlyList<string> goodRelics,
        IReadOnlyList<string> avoidRelics,
        IReadOnlyList<string>? avoidCards = null,
        int desiredMinDeckSize = 20,
        int desiredMaxDeckSize = 25,
        int lockCoreCardCount = 2,
        int lockEvidenceScore = 28)
    {
        return new AiBuildArchetype
        {
            CharacterId = characterId,
            BuildId = buildId,
            DisplayName = displayName,
            Tier = tier,
            CoreCards = coreCards,
            SupportCards = supportCards,
            AvoidCards = avoidCards ?? [],
            KeyRelics = keyRelics,
            GoodRelics = goodRelics,
            AvoidRelics = avoidRelics,
            DesiredMinDeckSize = desiredMinDeckSize,
            DesiredMaxDeckSize = desiredMaxDeckSize,
            LockCoreCardCount = lockCoreCardCount,
            LockEvidenceScore = lockEvidenceScore
        };
    }
}
